title: Tom√°s O'Malley # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: 
  <br>Currently a 3rd year student student studying software development @ Galway Mayo Institute of Technology.<br>
  <br>I began with computers at a young age, and accumulated a collection of college work from the past fewyears.Here are some of those projects.<br>
  <br>Some of my hobbies include PC building , Bike building and collection Analog audio gear such as Vinyl<br>
  <br>
  <a href="https://stackoverflow.com/users/13356579/omalleytomas98?tab=profile">Stack overflow</a> 
  <br>
  <a href="https://www.linkedin.com/in/tomas-omalley-09b997182/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
